import Header from "@/components/common/Header";
import ReduxndQueryWrapper from "@/components/home/ReduxndQueryWrapper";
import Footer from "@/components/common/Footer";
import BreadCrumb from "@/components/common/BreadCrumb";

export const metadata = {
  title: "Eltribo",
  description: "Generated by Next.js",
};

export default function RootLayout({ children }) {
  return (
    <>
      <ReduxndQueryWrapper>
        <Header />
      </ReduxndQueryWrapper>
      <BreadCrumb />

      {children}
      <Footer />
    </>
  );
}
